export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const GET_COMPANY_NAME = "GET_COMPANY_NAME";
export const ADD_COMPANY_NAME = "ADD_COMPANY_NAME";
export const DELETE_COMPANY_NAME = "DELETE_COMPANY_NAME";
export const ADD_FAVORITE_MENTION = "ADD_FAVORITE_MENTION";
export const DELETE_FAVORITE_MENTION = "DELETE_FAVORITE_MENTION";
export const ADD_PLATFORM = "ADD_PLATFORM";
export const DELETE_PLATFORM = "DELETE_PLATFORM";
