export const SIGNUP_ACTION = "SIGNUP_ACTION";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";

export const SHOW_ONLY_FAVORITES = "SHOW_ONLY_FAVORITES";
export const SHOW_ALL_MENTIONS = "SHOW_ALL_MENTIONS";
export const UPDATE_COMPANY_NAME = "UPDATE_COMPANY_NAME";
export const IS_LOADING_ON = "IS_LOADING_ON";
export const IS_LOADING_OFF = "IS_LOADING_OFF";
